name: Build

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: write

jobs:
  run-linters:
    name: Build
    runs-on: default
    steps:

      - name: Run build
        run: echo "npm run build:win" 
      - name: complete status
        run: echo "Build complete"


